machine:
  image: eu.registry.lttle.cloud/laurci/lttle-by-lttle-api:latest
  name: api
  namespace: lbl
  resources:
    cpu: 1
    memory: 128
  mode:
    flash:
      strategy:
        listen-on-port: 4477
      timeout: 2
  depends-on:
    - name: db
  restart-policy: always
  environment:
    DATABASE_URL: "postgresql://lbl:L6NyLVNdwmpk@db-internal.lbl.svc.lttle.local:5432/lbl"
    API_KEY: "eypadtJAckwZ"
---
service:
  name: api-http
  namespace: lbl
  target:
    name: api
    port: 4477
    protocol: http
  bind:
    external:
      host: lbl-api-laurci.eu.lttle.host
      protocol: https
---
service:
  name: api-device
  namespace: lbl
  target:
    name: api
    port: 4477
    protocol: http
  bind:
    external:
      host: lbl-api-device-laurci.eu.lttle.host
      protocol: http
