services:
  prometheus:
    image: prom/prometheus:v3.0.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-otlp-receiver
    ports:
      - "127.0.0.1:9090:9090"
      - "10.1.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/config.yml
    ports:
      - "127.0.0.1:3100:3100"
      - "10.1.0.1:3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "9898:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro

volumes:
  prom_data:
  loki_data:
  grafana_data:
